/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package livraria.view;

import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import livraria.control.Conexao;
import livraria.control.DaoLivro;
import livraria.model.Livro;
import livraria.control.DaoItemCarrinho;
import livraria.model.ItemCarrinho;
import java.util.Locale;
/**
 *
 * @author Felipe
 */
public class GuiCarrinho extends javax.swing.JFrame {

    /**
     * Creates new form GuiCarrinho
     */
    public GuiCarrinho() {
        initComponents();
        Locale.setDefault(Locale.UK);
        carregaCarrinho();
        
    }
    
  
    
    public void carregaCarrinho(){
            DaoItemCarrinho daoItemCarrinho = new DaoItemCarrinho(Conexao.getConnection());

            List<ItemCarrinho> carrinho = new ArrayList<>();

            try {
                carrinho = daoItemCarrinho.listaCarrinho();
            } catch (SQLException ex) {
                Logger.getLogger(GuiEstoque.class.getName()).log(Level.SEVERE, null, ex);
            }
                       
           // System.out.println(carrinho);
             
           
            DefaultTableModel modCarrinho = (DefaultTableModel)tblCarrinho.getModel();

            Double total =0.0;
            
            Object itemCarrinho[] = new Object[6];

            for(int j=0; j<carrinho.size(); j++){

                itemCarrinho[0]=carrinho.get(j).getIdItem();
                itemCarrinho[1]=carrinho.get(j).getTitulo();
                itemCarrinho[2]=carrinho.get(j).getAutor();
                itemCarrinho[3]=String.format("%.2f",carrinho.get(j).getValorOriginal()).replace(".", ",");
                itemCarrinho[4]=carrinho.get(j).getQtdeItem();
                itemCarrinho[5]=String.format("%.2f",carrinho.get(j).getSubTotalItem()).replace(".",",");
               

                modCarrinho.addRow(itemCarrinho);
                
             total += carrinho.get(j).getSubTotalItem();
 
            };
            
            
            lblTotal.setText("R$ " + String.format("%.2f", total));
            
       }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrinho = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnFinaliza = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLimpaCarrinho = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        mnVitrine = new javax.swing.JMenuItem();
        mnCarrinho = new javax.swing.JMenuItem();
        mnEstoque = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("TblCarrinho"); // NOI18N

        tblCarrinho.setAutoCreateRowSorter(true);
        tblCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Item", "Título", "Autor", "Preço", "Qtde", "Valor a pagar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarrinho);

        jLabel10.setText("Total ");

        btnFinaliza.setText("Finalizar Pedido");
        btnFinaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carrinho");

        btnLimpaCarrinho.setText("Limpar Carrinho");
        btnLimpaCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaCarrinhoActionPerformed(evt);
            }
        });

        jMenu4.setText("Telas");

        mnVitrine.setText("Vitrine");
        mnVitrine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVitrineActionPerformed(evt);
            }
        });
        jMenu4.add(mnVitrine);

        mnCarrinho.setText("Carrinho");
        mnCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCarrinhoActionPerformed(evt);
            }
        });
        jMenu4.add(mnCarrinho);

        mnEstoque.setText("Estoque");
        mnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEstoqueActionPerformed(evt);
            }
        });
        jMenu4.add(mnEstoque);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpaCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnFinaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFinaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpaCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnVitrineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVitrineActionPerformed
        GuiVitrine GuiVitrine= new GuiVitrine();
        GuiVitrine.setVisible(true);
        dispose();

    }//GEN-LAST:event_mnVitrineActionPerformed

    private void mnCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCarrinhoActionPerformed

       GuiCarrinho GuiCarrinho= new GuiCarrinho();
       GuiCarrinho.setVisible(true);
       dispose();
    }//GEN-LAST:event_mnCarrinhoActionPerformed

    private void mnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEstoqueActionPerformed

        GuiEstoque GuiEstoque= new GuiEstoque();
        GuiEstoque.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnEstoqueActionPerformed

    private void btnFinalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaActionPerformed
      
        JOptionPane.showMessageDialog(null,"Pedido realizado");
        
         

       DefaultTableModel modCarrinho = (DefaultTableModel)tblCarrinho.getModel();
       modCarrinho.setRowCount(0);
       carregaCarrinho();
        
        
    }//GEN-LAST:event_btnFinalizaActionPerformed

    private void btnLimpaCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaCarrinhoActionPerformed
    
        
        DaoItemCarrinho daoItemCarrinho = new DaoItemCarrinho(Conexao.getConnection());

        
       try {
            daoItemCarrinho.limpaCarrinho();
            
        } catch (SQLException ex) {
            Logger.getLogger(GuiVitrine.class.getName()).log(Level.SEVERE, null, ex);
        }
       DefaultTableModel modCarrinho = (DefaultTableModel)tblCarrinho.getModel();
       modCarrinho.setRowCount(0);
       carregaCarrinho();
        
    }//GEN-LAST:event_btnLimpaCarrinhoActionPerformed

     private void mnCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {                                       
       
        
        GuiCarrinho GuiCarrinho= new GuiCarrinho();
        GuiCarrinho.setVisible(true);
        
    } 
    
       private void mnVitrineMouseClicked(java.awt.event.MouseEvent evt) {                                       
       
        
        GuiVitrine GuiVitrine= new GuiVitrine();
        GuiVitrine.setVisible(true);
        
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCarrinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinaliza;
    private javax.swing.JButton btnLimpaCarrinho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JMenuItem mnCarrinho;
    private javax.swing.JMenuItem mnEstoque;
    private javax.swing.JMenuItem mnVitrine;
    private javax.swing.JTable tblCarrinho;
    // End of variables declaration//GEN-END:variables
}
